- hosts: jenkins_server
  become: yes
  tasks:

    - name: Ejecutando apt update
      apt:
        update_cache: yes

    - name: Ejecutanod apt upgrade
      apt:
        upgrade: yes

    - name: Instalando Paquetes necesarios
      apt:
        name: 
          - ca-certificates
          - curl
          - fontconfig
          - openjdk-17-jre
        state: present


    - name: Creando directorio de claves
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Descargando claves GPG de Docker
      get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Descargando claves GPG de Jenkins
      get_url:
        url: https://pkg.jenkins.io/debian/jenkins.io-2023.key
        dest: /usr/share/keyrings/jenkins-keyring.asc
        mode: '0644'

    - name: Añadiendo el repositorio de Docker
      lineinfile:
        path: /etc/apt/sources.list.d/docker.list
        line: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
        create: yes
      register: docker_repo

    - name: Añadiero el repositorio de Jenkins
      lineinfile:
        path: /etc/apt/sources.list.d/jenkins.list
        line: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian binary/"
        create: yes

    - name: Ejecutando Update
      apt:
        update_cache: yes

    - name: Instalando Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Instalando Jenkins
      apt:
        name: jenkins

